[package]
name = "proxy-tester-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
prost.workspace = true
proxy-tester-domain = { path = "../domain" }
thiserror.workspace = true
tonic.workspace = true
uuid.workspace = true

[build-dependencies]
tonic-build.workspace = true
protoc-bin-vendored = "3.2"
